### ISSUE TITLE
Container failed to exit within 10 seconds of signal 15 - using the force

### ISSUE THREAD

**Issue by Wonderfall** [hardware/mailserver#17]
Whenever I stop/restart the container, the following happens in syslog : 

``` 
Container xxxx failed to exit within 10 seconds of signal 15 - using the force
```

Nothing critical, but I'd like to know if I'm not the only one who experiences this.
As someone told me : _"A Jedi uses the Force for knowledge and defense, never for attack."_

**Comment by hardware** [comment]
Any warnings/errors in container logs during exit process ?

I think this is a kernel/docker bug after searching on Google/Stackoverflow, but I 'm not sure. if someone has an idea/fix..

**Comment by hardware** [comment]
I think I know what is wrong. I should use tini to lauch supervisord, not the startup script.  All signals send to the Docker container (e.g. using docker stop -> SIGTERM or docker kill -> SIGKILL) end up sent to tini, then tini send signals to the startup script which does not forward them to supervisord because it is not properly configured for this purpose.

**Solution :**

```
CMD ["tini", "--", "supervisord"]
```

And then, have supervisord launch first `/usr/local/bin/startup` and services. What do you think ?

Source :

https://github.com/krallin/tini/issues/8#issuecomment-146135930
https://github.com/jenkinsci/docker/issues/161#issuecomment-161569178

**Comment by xataz** [comment]
**Solution 4 :**
Use s6. [s6](https://github.com/skarnet/s6) replace tini and supervisor.
But a refactor of init script is needed, but why not ^^. I haven't try, but i think use s6 for my rutorrent image.

A good example is [gogs](https://github.com/gogits/gogs/tree/master/docker/s6), with init scripts for gogs, crond, openssh and syslogd.

What do you think ?

_Sorry for my english ^^_

**Comment by hardware** [comment]
I improved processes management using the exec command but the container can sometimes take more than 10 seconds to stop (amavisd take a long time before exiting). I advice you to increase the timeout like that :

```
docker stop -t 20 mailserver
docker-compose stop -t 20 mailserver
```

**Result :**

```
docker logs -f mailserver

2016-05-10 21:04:55,431 WARN received SIGTERM indicating exit request
2016-05-10 21:04:55,466 INFO waiting for amavisd, master, opendkim, freshclam, amavisd-milter, cron, clamd, opendmarc, rsyslog, dovecot to die
2016-05-10T21:04:55.467199+00:00 mail dovecot: master: Warning: Killed with signal 15 (by pid=5 uid=0 code=kill)
2016-05-10T21:04:55.477438+00:00 mail dovecot: imap: Server shutting down. in=4654 out=7244
2016-05-10T21:04:55.477449+00:00 mail dovecot: imap: Server shutting down. in=97 out=1876
2016-05-10T21:04:55.477455+00:00 mail dovecot: imap: Server shutting down. in=4557 out=7181
2016-05-10T21:04:55.477460+00:00 mail dovecot: imap: Server shutting down. in=293 out=797
2016-05-10T21:04:55.477467+00:00 mail dovecot: imap: Server shutting down. in=97 out=821
2016-05-10T21:04:55.477475+00:00 mail dovecot: imap: Server shutting down. in=325 out=861
2016-05-10 21:04:55,527 INFO stopped: dovecot (exit status 0)
2016-05-10 21:04:55,552 INFO stopped: rsyslog (exit status 0)
2016-05-10 21:04:57,571 INFO stopped: opendmarc (exit status 0)
2016-05-10 21:04:57,573 INFO stopped: cron (terminated by SIGTERM)
2016-05-10 21:05:01,580 INFO waiting for amavisd, master, opendkim, freshclam, amavisd-milter, clamd to die
2016-05-10 21:05:02,626 INFO stopped: opendkim (exit status 0)
2016-05-10 21:05:02,702 INFO stopped: master (terminated by SIGTERM)
2016-05-10 21:05:03,868 INFO stopped: clamd (exit status 0)
2016-05-10 21:05:04,871 INFO waiting for amavisd, freshclam, amavisd-milter to die
2016-05-10 21:05:08,257 INFO stopped: amavisd-milter (exit status 0)
2016-05-10 21:05:08,296 INFO stopped: freshclam (exit status 0)
2016-05-10 21:05:08,975 INFO stopped: amavisd (exit status 0)

21:04:55 -> 21:05:08 (13sec)
```

**Comment by thecem** [comment]
found this in journalctl logs for homeassistant container:

**...... failed to exit within 220 seconds of signal 15 - using the force**

**`Feb 13 21:01:56 hassio dockerd[321]: time="2021-02-13T21:01:56.312098661Z" level=info msg="Container 52dba521c8f2de3986ec980512cdc07cd2db346a256db78f83649169c24ba25c failed to exit within 220 seconds of signal 15 - using the force"`**

```
Feb 13 21:01:56 hassio 52dba521c8f2[321]: RuntimeError: Event loop is closed
Feb 13 21:01:56 hassio dockerd[321]: time="2021-02-13T21:01:56.312098661Z" level=info msg="Container 52dba521c8f2de3986ec980512cdc07cd2db346a256db78f83649169c24ba25c failed to exit within 220 seconds of signal 15 - using the force"
Feb 13 21:01:56 hassio 52dba521c8f2[321]: Top-level exception occurred in callback while processing a message
Feb 13 21:01:56 hassio 52dba521c8f2[321]: Traceback (most recent call last):
Feb 13 21:01:56 hassio 52dba521c8f2[321]:   File "/usr/local/lib/python3.8/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 84, in _wrap_callback_errors
Feb 13 21:01:56 hassio 52dba521c8f2[321]:     callback(message)
Feb 13 21:01:56 hassio 52dba521c8f2[321]:   File "/usr/local/lib/python3.8/site-packages/google_nest_sdm/google_nest_subscriber.py", line 58, in callback_wrapper
Feb 13 21:01:56 hassio 52dba521c8f2[321]:     future = asyncio.run_coroutine_threadsafe(async_callback(message), loop)
Feb 13 21:01:56 hassio 52dba521c8f2[321]:   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 930, in run_coroutine_threadsafe
Feb 13 21:01:56 hassio 52dba521c8f2[321]:     loop.call_soon_threadsafe(callback)
Feb 13 21:01:56 hassio 52dba521c8f2[321]:   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 764, in call_soon_threadsafe
Feb 13 21:01:56 hassio 52dba521c8f2[321]:     self._check_closed()
Feb 13 21:01:56 hassio 52dba521c8f2[321]:   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
Feb 13 21:01:56 hassio 52dba521c8f2[321]:     raise RuntimeError('Event loop is closed')
Feb 13 21:01:56 hassio 52dba521c8f2[321]: RuntimeError: Event loop is closed
Feb 13 21:01:56 hassio dockerd[334]: time="2021-02-13T21:01:56.400132651Z" level=info msg="shim reaped" id=52dba521c8f2de3986ec980512cdc07cd2db346a256db78f83649169c24ba25c
Feb 13 21:01:56 hassio dockerd[321]: time="2021-02-13T21:01:56.443236660Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Feb 13 21:01:56 hassio systemd[1]: var-lib-docker-overlay2-fbe7eccca458e0152422d840a743fa23b0bbf5052b3652d9a8a6fada989fb81d-merged.mount: Succeeded.
Feb 13 21:01:56 hassio systemd[1]: mnt-data-docker-overlay2-fbe7eccca458e0152422d840a743fa23b0bbf5052b3652d9a8a6fada989fb81d-merged.mount: Succeeded.
Feb 13 21:01:56 hassio 2d25542cf8d7[321]: 21-02-13 21:01:56 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning homeassistant application
Feb 13 21:01:56 hassio hassos-supervisor[1063]: 21-02-13 21:01:56 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning homeassistant application
Feb 13 21:01:56 hassio 2d25542cf8d7[321]: 21-02-13 21:01:56 INFO (MainThread) [supervisor.homeassistant] Update pulse/client.config: /data/tmp/homeassistant_pulse
Feb 13 21:01:56 hassio hassos-supervisor[1063]: 21-02-13 21:01:56 INFO (MainThread) [supervisor.homeassistant] Update pulse/client.config: /data/tmp/homeassistant_pulse
Feb 13 21:01:56 hassio systemd[1]: var-lib-docker-overlay2-d38acc0c561a1ad5e97dc885efe32e267fc82fe57694187828ea46418d4daf52\x2dinit-merged.mount: Succeeded.
Feb 13 21:01:56 hassio systemd[1]: mnt-data-docker-overlay2-d38acc0c561a1ad5e97dc885efe32e267fc82fe57694187828ea46418d4daf52\x2dinit-merged.mount: Succeeded.
Feb 13 21:01:57 hassio dockerd[334]: time="2021-02-13T21:01:57.066153316Z" level=warning msg="runtime v1 is deprecated since containerd v1.4, consider using runtime v2"
Feb 13 21:01:57 hassio dockerd[334]: time="2021-02-13T21:01:57.066675344Z" level=info msg="shim containerd-shim started" address="unix:///run/containerd/s/481ee6d3325dad7054bc596767990b4f5588829b84d72779e2f7faf872ea9a9c" debug=false pid=23631
Feb 13 21:01:57 hassio 2d25542cf8d7[321]: 21-02-13 21:01:57 INFO (SyncWorker_2) [supervisor.docker.homeassistant] Starting Home Assistant homeassistant/qemux86-64-homeassistant with version 2021.2.3
Feb 13 21:01:57 hassio hassos-supervisor[1063]: 21-02-13 21:01:57 INFO (SyncWorker_2) [supervisor.docker.homeassistant] Starting Home Assistant homeassistant/qemux86-64-homeassistant with version 2021.2.3
Feb 13 21:01:57 hassio hassos-supervisor[1063]: 21-02-13 21:01:57 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
Feb 13 21:01:57 hassio 2d25542cf8d7[321]: 21-02-13 21:01:57 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
Feb 13 21:01:57 hassio c3725752789f[321]: [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
Feb 13 21:01:57 hassio c3725752789f[321]: [s6-init] ensuring user provided files have correct perms...exited 0.
Feb 13 21:01:57 hassio c3725752789f[321]: [fix-attrs.d] applying ownership & permissions fixes...
Feb 13 21:01:57 hassio c3725752789f[321]: [fix-attrs.d] done.
Feb 13 21:01:57 hassio c3725752789f[321]: [cont-init.d] executing container initialization scripts...
Feb 13 21:01:57 hassio c3725752789f[321]: [cont-init.d] udev.sh: executing...
Feb 13 21:01:57 hassio 2338dc00fedf[321]: 13 Feb 22:01:57 - [info] [debug:b10f5496.8d0338] {"name":"Garagentor 1","service_name":"","service_type":"GarageDoorOpener","characteristic":"FirmwareRevision","cachedValue":"0.6.2"}
Feb 13 21:01:57 hassio 2338dc00fedf[321]: 13 Feb 22:01:57 - [info] [debug:b10f5496.8d0338] {"name":"Garagentor 2","service_name":"","service_type":"GarageDoorOpener","characteristic":"FirmwareRevision","cachedValue":"0.6.2"}
Feb 13 21:01:57 hassio c3725752789f[321]: [22:01:57] INFO: Using udev information from host
Feb 13 21:01:57 hassio c3725752789f[321]: [cont-init.d] udev.sh: exited 0.
Feb 13 21:01:57 hassio c3725752789f[321]: [cont-init.d] done.
Feb 13 21:01:57 hassio c3725752789f[321]: [services.d] starting services
Feb 13 21:01:57 hassio c3725752789f[321]: [services.d] done.
Feb 13 21:01:57 hassio 2338dc00fedf[321]: 13 Feb 22:01:57 - [info] [server:Home Assistant] Connecting to http://supervisor/core

```
