### ISSUE TITLE
AfterLogic :: Webmail Lite

### ISSUE THREAD

**Issue by denji** [hardware/mailserver#266]
* https://github.com/afterlogic/webmail-lite-8
* https://github.com/afterlogic/webmail-lite
* Demo: https://lite.afterlogic.com/

**Comment by hardware** [comment]
I will look closely at this project, rainloop on its side, no longer seems to be maintained. Thanks for the heads up.

**Comment by hardware** [comment]
I created a docker image here : https://github.com/hardware/afterlogic-webmail-lite

But I can't figure out why imap authentication doesn't work. The webmail does not even try to communicate with the mail server, an exception is thrown before any connection attempt.

I tried with PHP 7.1 and 7.2 without success. No errors in Nginx and PHP logs.

<details>
<summary>Afterlogic Webmail Lite debug logs</summary>

```
[08:38:46.00][b45e63c7] [POST(4)][ip:xx.xx.xx.xx] /?/Api/
[08:38:46.00][b45e63c7] POST > [Module, Method, TenantName, Parameters]
[08:38:46.00][b45e63c7]
[08:38:46.00][b45e63c7] API: StandardLoginFormWebclient::Login
[08:38:46.00][b45e63c7] Execute subscription: AdminAuth::onLogin
[08:38:46.01][b45e63c7] Execute subscription: Mail::onLogin
[08:38:46.01][b45e63c7] Event: 0 > login-failed: contact@domain.tld
[08:38:46.01][b45e63c7] Aurora\System\Exceptions\ApiException: ApiException in /afterlogic-webmail-lite/modules/Core/Module.php:1840

Stack trace:
#0 [internal function]: Aurora\Modules\Core\Module->Login('contact@domain.tld', 'xxxxxxxxxxx', '', false)
#1 /afterlogic-webmail-lite/system/Module/AbstractModule.php(875): call_user_func_array(Array, Array)
#2 /afterlogic-webmail-lite/system/Module/Decorator.php(42): Aurora\System\Module\AbstractModule->CallMethod('Login', Array)
#3 /afterlogic-webmail-lite/modules/StandardLoginFormWebclient/Module.php(45): Aurora\System\Module\Decorator->__call('Login', Array)
#4 [internal function]: Aurora\Modules\StandardLoginFormWebclient\Module->Login('contact@domain.tld', 'xxxxxxxxxxx', '', false)
#5 /afterlogic-webmail-lite/system/Module/AbstractModule.php(875): call_user_func_array(Array, Array)
#6 /afterlogic-webmail-lite/modules/Core/Module.php(535): Aurora\System\Module\AbstractModule->CallMethod('Login', Array, true)
#7 [internal function]: Aurora\Modules\Core\Module->EntryApi()
#8 /afterlogic-webmail-lite/system/Module/AbstractModule.php(620): call_user_func_array(Array, Array)
#9 /afterlogic-webmail-lite/system/Module/Manager.php(690): Aurora\System\Module\AbstractModule->RunEntry('api')
#10 /afterlogic-webmail-lite/system/Application.php(88): Aurora\System\Module\Manager->RunEntry('api')
#11 /afterlogic-webmail-lite/index.php(21): Aurora\System\Application::Start()
#12 {main}
```

</details>

<details>
<summary>Compatibility test</summary>

![](https://i.imgur.com/AbWH7Ow.png)

</details>


<details>
<summary>Mail server settings</summary>

![](https://i.imgur.com/geQd8Em.png)

</details>

Do you have an ide before I open an issue ?

**Comment by navossoc** [comment]
I'm using roundcubemail 1.3.6, it's very "old", but pretty stable.

I'll take a look later 🗡

[]'s

**Comment by navossoc** [comment]
Well I did it, not sure what is exactly happening...

The first error was:
> The username or password you entered is incorrect. (Not enough details required to establish connection.)

Simple enough, I just set up the database credentials and created the tables.

> The username or password you entered is incorrect.

No connection to IMAP as you said...

What I did is:
```
docker cp afterlogic-webmail-lite:/afterlogic-webmail-lite /mnt/docker/webmail2
```

And changed the mount on `docker-compose.yml` to:
```
    volumes:
      - /mnt/docker/webmail2:/afterlogic-webmail-lite
```

After that it start working like magic.

Looks like the setup on MySQL is not working properly, it is missing some entities on the `au_eav_entities` table.

Maybe is something related to permissions? I didn't dig further.

[]'s

**Comment by hardware** [comment]
I opened an issue here : https://github.com/afterlogic/webmail-lite-8/issues/22

**Comment by navossoc** [comment]
Well, that explains why changing the mount later solves the problem 😎 

[]'s

**Comment by hardware** [comment]
AfterLogic Webmail Lite docker image is ready. Initial setup is available [here](https://github.com/hardware/mailserver/wiki/AfterLogic-Webmail-Lite-initial-configuration). This webmail is not full-featured as rainloop but an alternative is always welcome.

**Comment by navossoc** [comment]
I do not know, but I think maybe it will be better to check if AfterLogic Webmail has already configured (`config.json` or empty folder maybe?).

Why I'm saying this?
Well, if you diff the `settings` folder from the .zip file and the `settings` folder that has been created inside the container, you will see there are a lot of things that are different between them and not only `AutocreateMailAccountOnNewUserFirstLogin` setting.

**Comment by hardware** [comment]
Yeah, but I don't know how to properly handle zip preconfigured settings inside the container after an update, so I let the webmail generate the files it needs and then the administrator just has to change the configuration at his convenience. I do not know if it's the best solution but it works well.

**Comment by navossoc** [comment]
>  I don't know how to properly handle zip preconfigured settings inside the container after an update

Well, me neither.
Sorry but I don't have any advice about it.

About the diffs:
`afterlogic-webmail-lite/settings` is the container folder and `data` is the original zip folder.

```
$ diff -rb -C 1 data/settings/ afterlogic-webmail-lite/settings/
Only in afterlogic-webmail-lite/settings/: config.json
Only in afterlogic-webmail-lite/settings/: config.json.bak
diff -rb -C 1 data/settings/modules/ChangePasswordWebclient.config.json afterlogic-webmail-lite/settings/modules/ChangePasswordWebclient.config.json
*** data/settings/modules/ChangePasswordWebclient.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/ChangePasswordWebclient.config.json	2018-07-20 19:00:57.487551110 -0300
***************
*** 2,4 ****
      "Disabled": [
!         true,
          "bool"
--- 2,4 ----
      "Disabled": [
! 		false,
  		"bool"
diff -rb -C 1 data/settings/modules/Core.config.json afterlogic-webmail-lite/settings/modules/Core.config.json
*** data/settings/modules/Core.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/Core.config.json	2018-07-20 19:00:57.463533887 -0300
***************
*** 59,61 ****
      "PostLoginErrorRedirectUrl": [
!         ".\/",
          "string"
--- 59,61 ----
      "PostLoginErrorRedirectUrl": [
!         "./",
          "string"
***************
*** 68,70 ****
      "ProductName": [
!         "Afterlogic WebMail Lite PHP",
          "string"
--- 68,70 ----
  	"ProductName": [
! 		"Unknown",
          "string"
diff -rb -C 1 data/settings/modules/CoreWebclient.config.json afterlogic-webmail-lite/settings/modules/CoreWebclient.config.json
*** data/settings/modules/CoreWebclient.config.json	2018-04-25 07:17:42.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/CoreWebclient.config.json	2018-07-20 19:01:20.695367314 -0300
***************
*** 42,44 ****
      "EntryModule": [
!         "mail",
          "string"
--- 42,44 ----
      "EntryModule": [
!         "",
          "string"
***************
*** 50,55 ****
      "HeaderModulesOrder": [
!         [
!             "mail",
!             "contacts"
!         ],
          "array"
--- 50,52 ----
      "HeaderModulesOrder": [
!         [],
          "array"
***************
*** 114,118 ****
          [
!             "Default",
!             "DeepForest",
!             "Funny"
          ],
--- 111,113 ----
          [
!             "Default"
          ],
Only in afterlogic-webmail-lite/settings/modules: CoreWebclient.config.json.bak
diff -rb -C 1 data/settings/modules/DropboxAuthWebclient.config.json afterlogic-webmail-lite/settings/modules/DropboxAuthWebclient.config.json
*** data/settings/modules/DropboxAuthWebclient.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/DropboxAuthWebclient.config.json	2018-07-20 19:00:57.503562592 -0300
***************
*** 6,8 ****
      "Scopes": [
!         "auth",
          "string"
--- 6,8 ----
      "Scopes": [
!         "",
          "string"
diff -rb -C 1 data/settings/modules/Dropbox.config.json afterlogic-webmail-lite/settings/modules/Dropbox.config.json
*** data/settings/modules/Dropbox.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/Dropbox.config.json	2018-07-20 19:00:57.471539628 -0300
***************
*** 2,4 ****
      "Disabled": [
!         true,
          "bool"
--- 2,4 ----
  	"Disabled": [
! 		false,
  		"bool"
diff -rb -C 1 data/settings/modules/MailAuthCpanel.config.json afterlogic-webmail-lite/settings/modules/MailAuthCpanel.config.json
*** data/settings/modules/MailAuthCpanel.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/MailAuthCpanel.config.json	2018-07-20 19:00:57.499559722 -0300
***************
*** 2,4 ****
      "Disabled": [
!         true,
          "bool"
--- 2,4 ----
      "Disabled": [
! 		false,
  		"bool"
diff -rb -C 1 data/settings/modules/MailChangePasswordCpanelPlugin.config.json afterlogic-webmail-lite/settings/modules/MailChangePasswordCpanelPlugin.config.json
*** data/settings/modules/MailChangePasswordCpanelPlugin.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/MailChangePasswordCpanelPlugin.config.json	2018-07-20 19:00:57.507565462 -0300
***************
*** 2,4 ****
      "Disabled": [
!         true,
          "bool"
--- 2,4 ----
  	"Disabled": [
! 		false,
  		"bool"
***************
*** 6,10 ****
      "SupportedServers": [
!         [
!             "*"
!         ],
          "array"
--- 6,8 ----
  	"SupportedServers": [
! 		["*"],
  		"array"
diff -rb -C 1 data/settings/modules/MailChangePasswordPoppassdPlugin.config.json afterlogic-webmail-lite/settings/modules/MailChangePasswordPoppassdPlugin.config.json
*** data/settings/modules/MailChangePasswordPoppassdPlugin.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/MailChangePasswordPoppassdPlugin.config.json	2018-07-20 19:00:57.487551110 -0300
***************
*** 2,4 ****
      "Disabled": [
!         true,
          "bool"
--- 2,4 ----
  	"Disabled": [
! 		false,
  		"bool"
***************
*** 6,10 ****
      "SupportedServers": [
!         [
!             "*"
!         ],
          "array"
--- 6,8 ----
  	"SupportedServers": [
! 		["*"],
  		"array"
diff -rb -C 1 data/settings/modules/Mail.config.json afterlogic-webmail-lite/settings/modules/Mail.config.json
*** data/settings/modules/Mail.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/Mail.config.json	2018-07-20 19:03:12.494963868 -0300
***************
*** 14,16 ****
      "AllowDefaultAccountForUser": [
!         true,
          "bool"
--- 14,16 ----
  	"AllowDefaultAccountForUser": [
! 		false,
  		"bool"
diff -rb -C 1 data/settings/modules/MailNotesPlugin.config.json afterlogic-webmail-lite/settings/modules/MailNotesPlugin.config.json
*** data/settings/modules/MailNotesPlugin.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/MailNotesPlugin.config.json	2018-07-20 19:00:57.503562592 -0300
***************
*** 2,4 ****
      "Disabled": [
!         true,
          "bool"
--- 2,4 ----
  	"Disabled": [
! 		false,
  		"bool"
diff -rb -C 1 data/settings/modules/MailSaveMessageAsPdfPlugin.config.json afterlogic-webmail-lite/settings/modules/MailSaveMessageAsPdfPlugin.config.json
*** data/settings/modules/MailSaveMessageAsPdfPlugin.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/MailSaveMessageAsPdfPlugin.config.json	2018-07-20 19:00:57.487551110 -0300
***************
*** 2,4 ****
      "Disabled": [
!         true,
          "bool"
--- 2,4 ----
      "Disabled": [
! 		false,
  		"bool"
diff -rb -C 1 data/settings/modules/MailTnefWebclientPlugin.config.json afterlogic-webmail-lite/settings/modules/MailTnefWebclientPlugin.config.json
*** data/settings/modules/MailTnefWebclientPlugin.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/MailTnefWebclientPlugin.config.json	2018-07-20 19:00:57.487551110 -0300
***************
*** 2,4 ****
      "Disabled": [
!         true,
          "bool"
--- 2,4 ----
      "Disabled": [
! 		false,
  		"bool"
diff -rb -C 1 data/settings/modules/OAuthIntegratorWebclient.config.json afterlogic-webmail-lite/settings/modules/OAuthIntegratorWebclient.config.json
*** data/settings/modules/OAuthIntegratorWebclient.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/OAuthIntegratorWebclient.config.json	2018-07-20 19:00:57.475542499 -0300
***************
*** 9,10 ****
--- 9,14 ----
  	],
+     "OnlyPasswordForAccountCreate": [
+ 		true,
+ 		"book"
+ 	],
      "AllowNewUsersRegister": [
diff -rb -C 1 data/settings/modules/StandardLoginFormWebclient.config.json afterlogic-webmail-lite/settings/modules/StandardLoginFormWebclient.config.json
*** data/settings/modules/StandardLoginFormWebclient.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/StandardLoginFormWebclient.config.json	2018-07-20 19:00:57.483548240 -0300
***************
*** 30,32 ****
      "BottomInfoHtmlText": [
!         "Powered by \u003Ca href=\"https:\/\/afterlogic.org\/webmail-lite\" target=\"_blank\"\u003EAfterlogic WebMail Lite\u003C\/a\u003E",
          "string"
--- 30,32 ----
      "BottomInfoHtmlText": [
! 		"",
  		"string"
***************
*** 42,44 ****
      "UseDropdownLanguagesView": [
!         true,
          "bool"
--- 42,44 ----
  	"UseDropdownLanguagesView": [
! 		false,
  		"bool"
diff -rb -C 1 data/settings/modules/StandardRegisterFormWebclient.config.json afterlogic-webmail-lite/settings/modules/StandardRegisterFormWebclient.config.json
*** data/settings/modules/StandardRegisterFormWebclient.config.json	2018-04-25 07:17:32.000000000 -0300
--- afterlogic-webmail-lite/settings/modules/StandardRegisterFormWebclient.config.json	2018-07-20 19:00:57.503562592 -0300
***************
*** 22,24 ****
      "BottomInfoHtmlText": [
!         "Powered by \u003Ca href=\"https:\/\/afterlogic.org\/webmail-lite\" target=\"_blank\"\u003EAfterlogic WebMail Lite\u003C\/a\u003E",
          "string"
--- 22,24 ----
      "BottomInfoHtmlText": [
! 		"",
  		"string"
```

Things like `ProductName`, `EntryModule`, `HeaderModulesOrder`, `ThemeList`, etc...

--

There is a `Dockerfile` here from `afterlogic-webmail-lite 7`.
https://github.com/afterlogic/docker-webmail-lite

Not sure if that version has a data folder or how it works, it may worth to take a look later to see if there is any logic to handle the config files.

[]'s

**Comment by hardware** [comment]
Only the EntryModule is interesting :

```json
"EntryModule": [
  "mail",
  "string"
]
```

I leave the default values for other properties.
